name: Check Secrets

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

        env:
          RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
          RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
          TEST_1: ${{ secrets.TEST_1 }}
          TEST_2: ${{ secrets.TEST_2 }}
          RS_PUB_KEY2: ${{ secrets.RS_PUB_KEY }}
jobs:
  check-secrets:
    name: Verify Actions Secrets
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-2022,
              arch: x86_64,
              vcpkg-triplet: x64-windows-static,
            }
          # - { target: aarch64-pc-windows-msvc, os: windows-2022, arch: aarch64 }
    steps:
      - name: Use Secret in Environment
        run: |
          echo "RS_PUB_KEY Key is: ${{ env.RS_PUB_KE }} "
          echo "RENDEZVOUS_SERVER is: ${{ env.RENDEZVOUS_SERVER }} "
          echo "TEST_2 is: ${{ env.TEST_2 }}"
          echo "TEST_1 is: env.TEST_1 "
          # Your build steps here
