name: Check Secrets

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"
    secrets:
      RS_PUB_KEY:
        required: true
      RENDEZVOUS_SERVER:
        required: true
      MACOS_CODESIGN_IDENTITY:
        required: true
      MACOS_P12_BASE64:
        required: true
      MACOS_P12_PASSWORD:
        required: true
  workflow_dispatch:  # Allows manual triggering of the workflow

#env:
 # RS_PUB_KEY: "${{ secrets.RS_PUB_KEY }}"
 # RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
 # MACOS_CODESIGN_IDENTITY: ${{ secrets.MACOS_CODESIGN_IDENTITY }}
 # MACOS_P12_BASE64: ${{ secrets.MACOS_P12_BASE64 }}
 # MACOS_P12_PASSWORD: ${{ secrets.MACOS_P12_PASSWORD }}
 # RS_PUB_KEY2: ${{ secrets.RS_PUB_KEY }}
jobs:
  check-secrets:
    name: Verify Actions Secrets
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-2022,
              arch: x86_64,
              vcpkg-triplet: x64-windows-static,
            }
          # - { target: aarch64-pc-windows-msvc, os: windows-2022, arch: aarch64 }
    steps:
      - name: Use Secret in Environment
        run: |
          echo "RS_PUB_KEY Key is: ${{ secrets.RS_PUB_KEY }}"
          echo " MACOS_P12_BASE64 is: ${{ secrets.MACOS_P12_BASE64 }}"
          echo "MACOS_CODESIGN_IDENTITY is: ${{ secrets.MACOS_CODESIGN_IDENTITY }} "
          
  build-for-macOS:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-apple-darwin,
              os: macos-13, #macos-latest or macos-14 use M1 now, https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#:~:text=14%20GB-,macos%2Dlatest%20or%20macos%2D14,-The%20macos%2Dlatestlabel
              extra-build-args: "",
              arch: x86_64,
            }
          - {
              target: aarch64-apple-darwin,
              os: macos-latest,
              # extra-build-args: "--disable-flutter-texture-render", # disable this for mac, because we see a lot of users reporting flickering both on arm and x64, and we can not confirm if texture rendering has better performance if htere is no vram, https://github.com/rustdesk/rustdesk/issues/6296
              extra-build-args: "",
              arch: aarch64,
            }
    steps:
      - name: Check if statement
        if: ${{ secrets.MACOS_P12_BASE64 }} != null
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_P12_BASE64 }}
          p12-password: ${{ secrets.MACOS_P12_PASSWORD }}
          keychain: rustdesk


