name: Check Secrets

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  RS_PUB_KEY: "${{ secrets.RS_PUB_KEY }}"
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  MACOS_CODESIGN_IDENTITY: ${{ secrets.MACOS_CODESIGN_IDENTITY }}
  MACOS_P12_BASE64: ${{ secrets.MACOS_P12_BASE64 }}
  RS_PUB_KEY2: ${{ secrets.RS_PUB_KEY }}
jobs:
  check-secrets:
    name: Verify Actions Secrets
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-2022,
              arch: x86_64,
              vcpkg-triplet: x64-windows-static,
            }
          # - { target: aarch64-pc-windows-msvc, os: windows-2022, arch: aarch64 }
    steps:
      - name: Use Secret in Environment
        run: |
          echo "RS_PUB_KEY Key is: $env.RS_PUB_KEY"
          echo " MACOS_P12_BASE64 is: ${{ env.MACOS_P12_BASE64 }}"
          echo "MACOS_CODESIGN_IDENTITY is: ${{ secrets.MACOS_CODESIGN_IDENTITY }} "
      - name: Check if statement
        #if: env.MACOS_P12_BASE64 != null
        if: ${{ env.MACOS_P12_BASE64 }} != null
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ env.MACOS_P12_BASE64 }}
          p12-password: ${{ env.MACOS_P12_PASSWORD }}
          keychain: rustdesk

          
        
        


